version: "3.10"
services:
  app:
    container_name: "sockets_tz"
    build: .
    ports:
      - 8000:8000
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8080
    volumes:
    - ./app:/usr/src/app